"""Compression basis construction and cached error grid helpers.

Adapted from original compression notebook logic. Codex and ChatGPT helped
organize the cached error workflow and shared compression helpers.
"""

from __future__ import annotations

import time

import numpy as np

from common import DEFAULT_Q_GRID, DEFAULT_ERR_GRID, DEFAULT_R_STEP, DEFAULT_REFINE_LOCAL


def projector_onto_lowest_k_eigs(H: np.ndarray, k: int) -> np.ndarray:
    """Build the projector onto the lowest k eigenvectors of a matrix and return a matrix."""
    _, V = np.linalg.eigh(H)
    Vk = V[:, :k]
    return Vk @ Vk.T


def lowest_k_eigvals(H: np.ndarray, k: int) -> np.ndarray:
    """Return the lowest k eigenvalues of a symmetric matrix as a float array."""
    return np.linalg.eigvalsh(H)[:k].copy()


def reduced_lowest_k_eigvals(H: np.ndarray, B: np.ndarray, k: int) -> np.ndarray:
    """Project a matrix into basis B, diagonalize it, and return the lowest k eigenvalues."""
    Hr = B.T @ H @ B
    return np.linalg.eigvalsh(Hr)[:k].copy()


def _sorted_eigendecomposition_desc(A):
    """Return eigenpairs of a symmetric matrix sorted by descending eigenvalue."""
    mu, U = np.linalg.eigh(A)
    idx = np.argsort(mu)[::-1]
    return mu[idx], U[:, idx]


def _build_Q_from_hamiltonians(H_list, k):
    """Average projectors onto lowest k eigenspaces for a list of Hamiltonians."""
    Q = np.zeros_like(H_list[0], dtype=np.float64)
    for H in H_list:
        Q += projector_onto_lowest_k_eigs(H, k)
    Q /= float(len(H_list))

    mu, U = _sorted_eigendecomposition_desc(Q)
    return Q, mu, U


def _build_error_cache_from_hamiltonians(H_list, k, Vmin, Vmax):
    """Build a standardized compression error cache from a Hamiltonian list.

    This cached workflow was organized with Codex and ChatGPT to avoid repeated
    full eigensolves during rank searches.
    """
    lam_full = np.array([lowest_k_eigvals(H, k) for H in H_list], dtype=float)

    return {
        "H_list": H_list,
        "lam_full": lam_full,
        "k": int(k),
        "Vmin": float(Vmin),
        "Vmax": float(Vmax),
        "n_grid": int(len(H_list)),
    }


def build_Q_k(M0, M1, k, Vmin, Vmax, n_grid=DEFAULT_Q_GRID):
    """Build Q_k from affine matrices M0 and M1 over a scalar grid and return Q eigenpairs.

    Codex and ChatGPT helped package this compression basis construction into a
    reusable function for PMM compression experiments.
    """
    Vg = np.linspace(Vmin, Vmax, int(n_grid))
    H_list = [M0 + V * M1 for V in Vg]
    return _build_Q_from_hamiltonians(H_list, k)


def build_basis_from_Q_eigvecs(U_sorted, r):
    """Take sorted Q eigenvectors and integer r and return the first r basis vectors."""
    return U_sorted[:, :r]


def build_error_grid_cache(M0, M1, k, Vmin, Vmax, n_grid=DEFAULT_ERR_GRID):
    """Precompute affine Hamiltonians and low eigenvalues on a grid and return a cache dict."""
    Vg = np.linspace(Vmin, Vmax, int(n_grid))
    H_list = [M0 + V * M1 for V in Vg]
    cache = _build_error_cache_from_hamiltonians(H_list, k, Vmin, Vmax)
    cache["Vg"] = Vg
    return cache


def compression_error_from_cache(B, cache):
    """
 Compute e_{k,r} using precomputed full reference values on the error grid.
 """
    H_list = cache["H_list"]
    lam_full = cache["lam_full"]
    k = cache["k"]

    emax = 0.0
    for i, H in enumerate(H_list):
        lam_r = reduced_lowest_k_eigvals(H, B, k)
        err = float(np.max(lam_r - lam_full[i]))
        if err > emax:
            emax = err

    return emax


def make_r_error_oracle(U_sorted, cache):
    """
 Returns a memoized function get_error(r), so repeated r values
 are evaluated only once.

 This cached rank error function was generated by Codex and ChatGPT
 to make repeated compression searches cheaper.
 """
    error_cache = {}

    def get_error(r):
        """Evaluate cached compression error for integer rank r and return a float."""
        r = int(r)
        if r not in error_cache:
            B = build_basis_from_Q_eigvecs(U_sorted, r)
            error_cache[r] = compression_error_from_cache(B, cache)
        return error_cache[r]

    return get_error


def compute_r_star_coarse_then_refine_cached(
    U_sorted,
    cache,
    k,
    tol,
    n_pmm,
    r_step=DEFAULT_R_STEP,
    refine=DEFAULT_REFINE_LOCAL,
    get_error=None,
):
    """Search cached compression errors for the smallest rank meeting a tolerance and return an int.

    The coarse then refine structure was suggested by ChatGPT to
    keep the rank search readable while avoiding unnecessary repeated work.
    """
    if get_error is None:
        get_error = make_r_error_oracle(U_sorted, cache)

    r_values = list(range(k, n_pmm + 1, r_step))
    if r_values[-1] != n_pmm:
        r_values.append(n_pmm)

    r_star = None
    for r in r_values:
        e = get_error(r)
        if e <= tol:
            r_star = r
            break

    if r_star is None:
        return int(n_pmm)

    if (not refine) or (r_step == 1):
        return int(r_star)

    r_lo = max(k, r_star - r_step)
    r_hi = min(n_pmm, r_star)

    for r in range(r_lo, r_hi + 1):
        e = get_error(r)
        if e <= tol:
            return int(r)

    return int(r_star)


def compute_rstars_for_tolerances_cached(
    U_sorted,
    cache,
    k,
    tol_list,
    n_pmm,
    r_step=DEFAULT_R_STEP,
    refine=DEFAULT_REFINE_LOCAL,
):
    """Reuse cached compression errors across tolerances and return a tolerance to result dict.
    """
    get_error = make_r_error_oracle(U_sorted, cache)

    out = {}
    for tol in tol_list:
        r_star = compute_r_star_coarse_then_refine_cached(
            U_sorted,
            cache=cache,
            k=k,
            tol=tol,
            n_pmm=n_pmm,
            r_step=r_step,
            refine=refine,
            get_error=get_error,
        )
        out[tol] = {
            "r_star": r_star,
            "e_rstar": get_error(r_star),
        }

    return out


def build_true_Q_k(lipkin, k, Vmin, Vmax, n_grid=DEFAULT_Q_GRID):
    """
 Build Q_k directly from the true Lipkin Hamiltonian:
 Q_k = average of projectors onto the true lowest k eigenspaces.
 """
    Vg = np.linspace(Vmin, Vmax, int(n_grid))
    H_list = [np.asarray(lipkin.hamiltonian(V), dtype=np.float64) for V in Vg]
    return _build_Q_from_hamiltonians(H_list, k)


def prepare_pmm_compression(
    case,
    tol,
    n_grid_Q=DEFAULT_Q_GRID,
    n_grid_err=DEFAULT_ERR_GRID,
    r_step=DEFAULT_R_STEP,
    refine=DEFAULT_REFINE_LOCAL,
):
    """Build compression basis and r star diagnostics for one trained PMM case.

    This helper collects compression setup logic that was originally repeated
    in the Lipkin and pairing result notebooks. This was suggested by Codex.
    """
    x_min, x_max = -1.0, 1.0
    k = int(case["k"])
    n_pmm = int(case["n_pmm"])
    M0 = case["M0"]
    M1 = case["M1"]

    t0 = time.perf_counter()
    Q, mu, U = build_Q_k(M0, M1, k, x_min, x_max, n_grid=n_grid_Q)
    t1 = time.perf_counter()

    cache = build_error_grid_cache(M0, M1, k, x_min, x_max, n_grid=n_grid_err)
    t2 = time.perf_counter()

    get_error = make_r_error_oracle(U, cache)
    r_star = compute_r_star_coarse_then_refine_cached(
        U,
        cache=cache,
        k=k,
        tol=tol,
        n_pmm=n_pmm,
        r_step=r_step,
        refine=refine,
        get_error=get_error,
    )
    t3 = time.perf_counter()

    r_2k = min(2 * k, n_pmm)
    B_rstar = build_basis_from_Q_eigvecs(U, r_star)

    return {
        "tol": float(tol),
        "Q": Q,
        "mu_Q": mu,
        "U_Q": U,
        "r_star": int(r_star),
        "r_star_over_k": float(r_star / k),
        "e_rstar": float(get_error(r_star)),
        "r_2k": int(r_2k),
        "e_2k": float(get_error(r_2k)),
        "B_rstar": B_rstar,
        "Q_build_time_s": float(t1 - t0),
        "error_cache_time_s": float(t2 - t1),
        "r_search_time_s": float(t3 - t2),
        "compression_preprocess_time_s": float(t3 - t0),
    }
