"""Pairing model quench time evolution helpers.

Adapted from original time evolution notebook cells. Codex and ChatGPT helped
create many helper functions, especially for pair occupation observables and
the time evolution result structure.
"""

from __future__ import annotations

import time

import numpy as np
import torch
import torch.nn as nn

from baselines import count_parameters, set_torch_seed
from compression import build_basis_from_Q_eigvecs, build_true_Q_k
from common import GLOBAL_SEED, compute_error_stats_with_mse, scale_V_to_unit
from models import PairingModel


DEVICE = "cpu"
TORCH_DTYPE = torch.float64
DEFAULT_PMM_EVAL_BATCH_SIZE = 512


def sym_torch_matrix(A):
    """Symmetrize a torch matrix and return the symmetric tensor."""
    return 0.5 * (A + A.T)


def affine_torch_hamiltonian(M0, M1, x_scalar):
    """Combine M0, M1, and scalar x into one Hamiltonian tensor."""
    return M0 + x_scalar * M1


def batched_affine_torch_hamiltonian(M0, M1, x_values):
    """Build a batch of Hamiltonian tensors from M0, M1, and x values."""
    return M0.unsqueeze(0) + x_values.reshape(-1, 1, 1) * M1.unsqueeze(0)


def ground_state_from_torch_matrices(M0, M1, x_prep):
    """Diagonalize the prep Hamiltonian and return its ground state vector."""
    evals, evecs = torch.linalg.eigh(affine_torch_hamiltonian(M0, M1, x_prep))
    return evecs[:, 0]


def pairing_ground_state(pairing: PairingModel, g: float):
    """Diagonalize a pairing model at scalar g and return the ground energy and state vector."""
    H = pairing.hamiltonian(g)
    evals, evecs = np.linalg.eigh(H)
    return float(evals[0]), evecs[:, 0]


def pairing_survival_time_series(pairing: PairingModel, psi0, g: float, times):
    """Evaluate exact pairing survival probabilities for one g and time array."""
    H = pairing.hamiltonian(g)
    return hamiltonian_survival_time_series(H, psi0, times)


def hamiltonian_survival_time_series(H, psi0, times):
    """Evaluate survival probabilities from a Hamiltonian, initial state, and time array."""
    evals, evecs = np.linalg.eigh(H)
    coeffs = evecs.T.conj() @ psi0
    overlap_weights = np.abs(coeffs) ** 2
    phases = np.exp(-1j * np.outer(np.asarray(times, dtype=float), evals))
    amplitudes = phases @ overlap_weights
    return np.abs(amplitudes) ** 2


def pairing_pair_occupation_projector(pairing: PairingModel, level_index: int):
    """Pair occupation observable, represented here as a diagonal projector.

    This observable function was generated by Codex and ChatGPT.
    """
    level_index = int(level_index)
    O = np.zeros((pairing.dim, pairing.dim), dtype=np.float64)
    for i, state in enumerate(pairing.basis_states):
        O[i, i] = 1.0 if level_index in state else 0.0
    return O


def exact_time_series_for_observable(pairing: PairingModel, psi0, g: float, times, O):
    """Evaluate an exact observable time series for one pairing coupling and return an array."""
    H = pairing.hamiltonian(g)
    return hamiltonian_observable_time_series(H, psi0, times, O)


def hamiltonian_observable_time_series(H, psi0, times, O):
    """Evaluate observable expectations from a Hamiltonian, state, times, and observable matrix."""
    evals, evecs = np.linalg.eigh(H)
    coeffs = evecs.T.conj() @ psi0
    phases = np.exp(-1j * np.outer(np.asarray(times, dtype=float), evals))
    psi_t = (phases * coeffs[None, :]) @ evecs.T
    O_psi_t = psi_t @ O.T
    values = np.einsum("ti,ti->t", np.conjugate(psi_t), O_psi_t)
    return np.asarray(np.real_if_close(values), dtype=np.float64)


def canonical_observable_name(observable_name: str) -> str:
    """Normalize an observable name string and return the canonical name."""
    aliases = {
        "n0": "pair_occ_0",
        "n_last": "pair_occ_last",
    }
    return aliases.get(str(observable_name), str(observable_name))


def exact_observable_matrix_for_name(pairing: PairingModel, observable_name: str):
    """Return an exact model matrix observable, excluding survival probability."""
    observable_name = canonical_observable_name(observable_name)
    builders = {
        "pair_occ_0": lambda: pairing_pair_occupation_projector(pairing, 0),
        "pair_occ_last": lambda: pairing_pair_occupation_projector(pairing, pairing.n_levels - 1),
    }
    return builders[observable_name]()


def make_pairing_quench_observable_data(
    pnum,
    hnum,
    delta,
    g_prep,
    g_min,
    g_max,
    t_min,
    t_max,
    n_g_train,
    n_t_train,
    n_g_test,
    n_t_test,
    observable_name,
):
    """Build exact pairing quench train/test grids for flat PMM inputs and sequence baselines.

    Codex and ChatGPT helped turn the original notebook function into this shared
    data constructor for survival and pair occupation experiments.
    """
    observable_name = canonical_observable_name(observable_name)
    pairing = PairingModel(pnum=pnum, hnum=hnum, delta=delta)
    _, psi0 = pairing_ground_state(pairing, g_prep)
    observable_matrix = (
        None
        if observable_name == "survival"
        else exact_observable_matrix_for_name(pairing, observable_name)
    )

    g_train = np.linspace(g_min, g_max, int(n_g_train))
    t_train = np.linspace(t_min, t_max, int(n_t_train))
    g_test = np.linspace(g_min, g_max, int(n_g_test))
    t_test = np.linspace(t_min, t_max, int(n_t_test))

    Y_train = np.zeros((len(g_train), len(t_train)), dtype=np.float64)
    Y_test = np.zeros((len(g_test), len(t_test)), dtype=np.float64)

    for i, g in enumerate(g_train):
        if observable_name == "survival":
            Y_train[i, :] = pairing_survival_time_series(pairing, psi0, g, t_train)
        else:
            Y_train[i, :] = exact_time_series_for_observable(pairing, psi0, g, t_train, observable_matrix)

    for i, g in enumerate(g_test):
        if observable_name == "survival":
            Y_test[i, :] = pairing_survival_time_series(pairing, psi0, g, t_test)
        else:
            Y_test[i, :] = exact_time_series_for_observable(pairing, psi0, g, t_test, observable_matrix)

    g_train_scaled = scale_V_to_unit(g_train, g_min, g_max)
    g_test_scaled = scale_V_to_unit(g_test, g_min, g_max)
    t_train_scaled = scale_V_to_unit(t_train, t_min, t_max)
    t_test_scaled = scale_V_to_unit(t_test, t_min, t_max)

    X_train_seq = np.zeros((len(g_train), len(t_train), 2), dtype=np.float64)
    X_test_seq = np.zeros((len(g_test), len(t_test), 2), dtype=np.float64)

    for i, gsc in enumerate(g_train_scaled):
        X_train_seq[i, :, 0] = gsc
        X_train_seq[i, :, 1] = t_train_scaled

    for i, gsc in enumerate(g_test_scaled):
        X_test_seq[i, :, 0] = gsc
        X_test_seq[i, :, 1] = t_test_scaled

    G_train, T_train = np.meshgrid(g_train, t_train, indexing="ij")
    G_test, T_test = np.meshgrid(g_test, t_test, indexing="ij")

    X_train_pmm = np.stack(
        [scale_V_to_unit(G_train, g_min, g_max).ravel(), T_train.ravel()],
        axis=1,
    )
    X_test_pmm = np.stack(
        [scale_V_to_unit(G_test, g_min, g_max).ravel(), T_test.ravel()],
        axis=1,
    )

    return {
        "pairing": pairing,
        "psi0_exact": psi0,
        "observable_name": observable_name,
        "observable_matrix": observable_matrix,
        "g_prep": float(g_prep),
        "g_train": g_train,
        "t_train": t_train,
        "g_test": g_test,
        "t_test": t_test,
        "Y_train": Y_train,
        "Y_test": Y_test,
        "X_train_seq": X_train_seq,
        "X_test_seq": X_test_seq,
        "X_train_pmm": X_train_pmm,
        "X_test_pmm": X_test_pmm,
        "y_train_flat": Y_train.reshape(-1, 1),
        "y_test_flat": Y_test.reshape(-1, 1),
        "g_min": float(g_min),
        "g_max": float(g_max),
        "t_min": float(t_min),
        "t_max": float(t_max),
        "x_prep": float(scale_V_to_unit(np.array([g_prep]), g_min, g_max)[0]),
    }


def build_exact_quench_compression_basis(
    pairing: PairingModel,
    k: int,
    g_min: float,
    g_max: float,
    ranks,
    n_grid: int,
):
    """Build the Q_k basis for exact pairing Hamiltonian compression.

    This connects the time evolution experiment to the same compression
    framework used in the static pairing results, and was partially implemented by Codex.
    """
    ranks = [int(rank) for rank in ranks]

    Q, mu, U = build_true_Q_k(pairing, int(k), float(g_min), float(g_max), n_grid=int(n_grid))
    basis_by_rank = {rank: build_basis_from_Q_eigvecs(U, rank) for rank in ranks}
    return {
        "k": int(k),
        "g_min": float(g_min),
        "g_max": float(g_max),
        "n_grid": int(n_grid),
        "Q": Q,
        "mu_Q": mu,
        "U_Q": U,
        "basis_by_rank": basis_by_rank,
    }


def normalized_projected_state(B, psi0):
    """Project a state into basis B, normalize it, and return the state plus projection norm.
    """
    projected = B.T.conj() @ psi0
    norm = float(np.linalg.norm(projected))
    return projected / norm, norm


def evaluate_reduced_quench_on_grid(
    pairing: PairingModel,
    B,
    psi0,
    g_grid,
    t_grid,
    observable_name: str,
    observable_matrix=None,
):
    """Evaluate reduced exact quench dynamics in basis B and return predictions plus diagnostics.

    This reduced exact evaluation was organized with Codex and ChatGPT to make
    the compressed benchmark explicit before comparing against PMMs.
    """
    observable_name = canonical_observable_name(observable_name)
    psi0_r, psi0_projected_norm = normalized_projected_state(B, psi0)
    O_r = None
    if observable_name != "survival":
        O_r = B.T.conj() @ observable_matrix @ B

    g_grid = np.asarray(g_grid, dtype=float)
    t_grid = np.asarray(t_grid, dtype=float)
    Y = np.zeros((len(g_grid), len(t_grid)), dtype=np.float64)

    for i, g in enumerate(g_grid):
        H_r = B.T.conj() @ pairing.hamiltonian(float(g)) @ B
        if observable_name == "survival":
            Y[i, :] = hamiltonian_survival_time_series(H_r, psi0_r, t_grid)
        else:
            Y[i, :] = hamiltonian_observable_time_series(H_r, psi0_r, t_grid, O_r)

    return {
        "Y": Y,
        "psi0_projected_norm": psi0_projected_norm,
        "O_reduced": O_r,
    }


def evaluate_compressed_exact_quench_by_rank(data: dict, compression_basis: dict, ranks):
    """Evaluate compressed exact quench predictions for several ranks.

    Codex and ChatGPT helped organize this comparison layer so compression
    error and PMM learning error could be studied separately.
    """
    out = {}
    observable_name = canonical_observable_name(data["observable_name"])

    for rank in [int(rank) for rank in ranks]:
        B = compression_basis["basis_by_rank"][rank]
        train_eval = evaluate_reduced_quench_on_grid(
            data["pairing"],
            B,
            data["psi0_exact"],
            data["g_train"],
            data["t_train"],
            observable_name=observable_name,
            observable_matrix=data.get("observable_matrix"),
        )
        test_eval = evaluate_reduced_quench_on_grid(
            data["pairing"],
            B,
            data["psi0_exact"],
            data["g_test"],
            data["t_test"],
            observable_name=observable_name,
            observable_matrix=data.get("observable_matrix"),
        )
        Y_train_pred = train_eval["Y"]
        Y_test_pred = test_eval["Y"]
        out[rank] = {
            "rank": int(rank),
            "model_type": "compressed exact",
            "observable_name": observable_name,
            "B": B,
            "Y_train_pred": Y_train_pred,
            "Y_test_pred": Y_test_pred,
            "Y_test_pred_seq": Y_test_pred,
            "abs_error": np.abs(Y_test_pred - data["Y_test"]),
            "train_stats": compute_error_stats_with_mse(data["Y_train"], Y_train_pred),
            "test_stats": compute_error_stats_with_mse(data["Y_test"], Y_test_pred),
            "psi0_projected_norm": float(test_eval["psi0_projected_norm"]),
            "O_reduced": test_eval["O_reduced"],
        }

    return out


class PMMSurvivalTimeEvolution(nn.Module):
    """Torch PMM model for survival dynamics with a learned affine Hamiltonian.

    This model class was organized with Codex and ChatGPT from the original
    time evolution PMM experiment cells.
    """
    def __init__(
        self,
        n_pmm,
        init_scale=1e-2,
        dtype=TORCH_DTYPE,
        eval_batch_size=DEFAULT_PMM_EVAL_BATCH_SIZE,
    ):
        """Create survival PMM matrices from dimension, scale, dtype, and batch settings and returns None."""
        super().__init__()
        self.n = int(n_pmm)
        self.eval_batch_size = None if eval_batch_size is None else int(eval_batch_size)
        self.raw_M0 = nn.Parameter(init_scale * torch.randn(self.n, self.n, dtype=dtype))
        self.raw_M1 = nn.Parameter(init_scale * torch.randn(self.n, self.n, dtype=dtype))

    def sym_matrices(self):
        """Return the symmetrized PMM Hamiltonian matrices M0 and M1."""
        return sym_torch_matrix(self.raw_M0), sym_torch_matrix(self.raw_M1)

    def forward_batch(self, X, M0, M1, phi0):
        """Evaluate PMM survival for a batch of two column input rows and return predictions."""
        H_batch = batched_affine_torch_hamiltonian(M0, M1, X[:, 0])
        evals, evecs = torch.linalg.eigh(H_batch)
        coeffs = torch.matmul(evecs.transpose(-2, -1), phi0)
        overlap_weights = torch.abs(coeffs) ** 2
        t_values = X[:, 1].reshape(-1, 1)
        amp_real = torch.sum(overlap_weights * torch.cos(evals * t_values), dim=1)
        amp_imag = -torch.sum(overlap_weights * torch.sin(evals * t_values), dim=1)
        return (amp_real**2 + amp_imag**2).reshape(-1, 1)

    def forward(self, X, x_prep):
        """Evaluate PMM survival for all input rows, using batches if configured."""
        M0, M1 = self.sym_matrices()
        phi0 = ground_state_from_torch_matrices(M0, M1, x_prep)
        if self.eval_batch_size is None or X.shape[0] <= self.eval_batch_size:
            return self.forward_batch(X, M0, M1, phi0)
        chunks = [
            self.forward_batch(X[start : start + self.eval_batch_size], M0, M1, phi0)
            for start in range(0, X.shape[0], self.eval_batch_size)
        ]
        return torch.cat(chunks, dim=0)


class PMMObservableTimeEvolution(nn.Module):
    """Torch PMM model for observable dynamics with learned Hamiltonian and observable matrices.

    Codex and ChatGPT helped build this learned observable variant for the pair
    occupation time evolution experiments.
    """
    def __init__(
        self,
        n_pmm,
        init_scale=1e-2,
        dtype=TORCH_DTYPE,
        eval_batch_size=DEFAULT_PMM_EVAL_BATCH_SIZE,
    ):
        """Create observable PMM matrices from dimension, scale, dtype, and batch settings and returns None."""
        super().__init__()
        self.n = int(n_pmm)
        self.eval_batch_size = None if eval_batch_size is None else int(eval_batch_size)
        self.raw_M0 = nn.Parameter(init_scale * torch.randn(self.n, self.n, dtype=dtype))
        self.raw_M1 = nn.Parameter(init_scale * torch.randn(self.n, self.n, dtype=dtype))
        self.raw_O = nn.Parameter(init_scale * torch.randn(self.n, self.n, dtype=dtype))

    def sym_components(self):
        """Return symmetrized Hamiltonian matrices and the learned observable matrix."""
        return sym_torch_matrix(self.raw_M0), sym_torch_matrix(self.raw_M1), sym_torch_matrix(self.raw_O)

    def forward_batch(self, X, M0, M1, O, phi0):
        """Evaluate observable PMM predictions for a batch of two column input rows."""
        H_batch = batched_affine_torch_hamiltonian(M0, M1, X[:, 0])
        evals, evecs = torch.linalg.eigh(H_batch)
        coeffs = torch.matmul(evecs.transpose(-2, -1), phi0)
        t_values = X[:, 1].reshape(-1, 1)
        phase = torch.complex(torch.cos(evals * t_values), -torch.sin(evals * t_values))
        evecs_c = torch.complex(evecs, torch.zeros_like(evecs))
        coeffs_c = torch.complex(coeffs, torch.zeros_like(coeffs))
        phi_t = torch.matmul(evecs_c, (phase * coeffs_c).unsqueeze(-1)).squeeze(-1)
        O_c = torch.complex(O, torch.zeros_like(O))
        O_phi_t = torch.matmul(O_c, phi_t.unsqueeze(-1)).squeeze(-1)
        return torch.sum(torch.conj(phi_t) * O_phi_t, dim=1).real.reshape(-1, 1)

    def forward(self, X, x_prep):
        """Evaluate observable PMM predictions for all input rows, using batches if configured."""
        M0, M1, O = self.sym_components()
        phi0 = ground_state_from_torch_matrices(M0, M1, x_prep)
        if self.eval_batch_size is None or X.shape[0] <= self.eval_batch_size:
            return self.forward_batch(X, M0, M1, O, phi0)
        chunks = [
            self.forward_batch(X[start : start + self.eval_batch_size], M0, M1, O, phi0)
            for start in range(0, X.shape[0], self.eval_batch_size)
        ]
        return torch.cat(chunks, dim=0)


class PMMFixedObservableTimeEvolution(PMMObservableTimeEvolution):
    """Observable PMM variant with a fixed non trainable observable matrix.

    This variant separates learned observables from the dimension matched
    compressed observable comparison.
    """
    def __init__(
        self,
        O_fixed,
        init_scale=1e-2,
        dtype=TORCH_DTYPE,
        eval_batch_size=DEFAULT_PMM_EVAL_BATCH_SIZE,
    ):
        """Create a fixed observable PMM from an observable matrix and optimizer settings and returns None."""
        nn.Module.__init__(self)
        O_fixed = torch.as_tensor(O_fixed, dtype=dtype)

        self.n = int(O_fixed.shape[0])
        self.eval_batch_size = None if eval_batch_size is None else int(eval_batch_size)
        self.raw_M0 = nn.Parameter(init_scale * torch.randn(self.n, self.n, dtype=dtype))
        self.raw_M1 = nn.Parameter(init_scale * torch.randn(self.n, self.n, dtype=dtype))
        self.register_buffer("O_fixed", sym_torch_matrix(O_fixed).clone())

    def sym_components(self):
        """Return symmetrized Hamiltonian matrices and the fixed observable tensor."""
        return sym_torch_matrix(self.raw_M0), sym_torch_matrix(self.raw_M1), self.O_fixed


def _train_pmm_time_model(
    model,
    X_train,
    y_train,
    X_test,
    y_test,
    x_prep=0.0,
    epochs=4000,
    lr=1e-2,
    seed=GLOBAL_SEED,
    device=DEVICE,
    dtype=TORCH_DTYPE,
    verbose=True,
    print_every=500,
):
    """Train a torch PMM time model on flat arrays and return predictions, metrics, and model."""
    set_torch_seed(seed)
    model = model.to(device=device, dtype=dtype)
    X_train_t = torch.tensor(X_train, dtype=dtype, device=device)
    y_train_t = torch.tensor(y_train, dtype=dtype, device=device)
    X_test_t = torch.tensor(X_test, dtype=dtype, device=device)
    x_prep_t = torch.tensor(float(x_prep), dtype=dtype, device=device)

    optimizer = torch.optim.Adam(model.parameters(), lr=float(lr))
    loss_fn = nn.MSELoss()

    best_state = None
    best_loss = float("inf")
    best_epoch = 0
    t0 = time.perf_counter()

    for epoch in range(1, int(epochs) + 1):
        model.train()
        optimizer.zero_grad()
        pred = model(X_train_t, x_prep_t)
        loss = loss_fn(pred, y_train_t)
        loss.backward()
        optimizer.step()

        loss_value = float(loss.item())
        if loss_value < best_loss:
            best_loss = loss_value
            best_epoch = epoch
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

        if verbose and (epoch == 1 or epoch % int(print_every) == 0):
            print(f"PMM epoch {epoch:5d} | train mse = {loss_value:.6e}")

    train_time = time.perf_counter() - t0
    model.load_state_dict(best_state)
    model.eval()

    with torch.no_grad():
        y_train_pred = model(X_train_t, x_prep_t).cpu().numpy()
        y_test_pred = model(X_test_t, x_prep_t).cpu().numpy()

    return {
        "model": model,
        "parameter_count": count_parameters(model),
        "train_time_s": float(train_time),
        "best_epoch": int(best_epoch),
        "best_train_mse": float(best_loss),
        "y_train_pred_flat": y_train_pred,
        "y_test_pred_flat": y_test_pred,
        "train_stats": compute_error_stats_with_mse(y_train, y_train_pred),
        "test_stats": compute_error_stats_with_mse(y_test, y_test_pred),
    }


def train_pmm_survival_model(
    X_train,
    y_train,
    X_test,
    y_test,
    n_pmm=16,
    x_prep=0.0,
    epochs=4000,
    lr=1e-2,
    init_scale=1e-2,
    eval_batch_size=DEFAULT_PMM_EVAL_BATCH_SIZE,
    seed=GLOBAL_SEED,
    device=DEVICE,
    dtype=TORCH_DTYPE,
    verbose=True,
    print_every=500,
):
    """Train a survival PMM from flat train/test arrays and return a result dict.
    """
    model = PMMSurvivalTimeEvolution(
        n_pmm=n_pmm,
        init_scale=init_scale,
        dtype=dtype,
        eval_batch_size=eval_batch_size,
    )
    result = _train_pmm_time_model(
        model,
        X_train,
        y_train,
        X_test,
        y_test,
        x_prep=x_prep,
        epochs=epochs,
        lr=lr,
        seed=seed,
        device=device,
        dtype=dtype,
        verbose=verbose,
        print_every=print_every,
    )
    result["n_pmm"] = int(n_pmm)
    result["eval_batch_size"] = None if eval_batch_size is None else int(eval_batch_size)
    result["model_type"] = "PMM survival"
    result["learned_observable"] = False
    result["model_scope_note"] = (
        "Survival PMM learns a Hamiltonian; the survival observable is induced by the "
        "PMM initial state overlaps."
    )
    return result


def train_pmm_observable_model(
    X_train,
    y_train,
    X_test,
    y_test,
    n_pmm=16,
    x_prep=0.0,
    epochs=4000,
    lr=1e-2,
    init_scale=1e-2,
    eval_batch_size=DEFAULT_PMM_EVAL_BATCH_SIZE,
    seed=GLOBAL_SEED,
    device=DEVICE,
    dtype=TORCH_DTYPE,
    verbose=True,
    print_every=500,
):
    """Train a learned observable PMM from flat arrays and return a result dict.
    """
    model = PMMObservableTimeEvolution(
        n_pmm=n_pmm,
        init_scale=init_scale,
        dtype=dtype,
        eval_batch_size=eval_batch_size,
    )
    result = _train_pmm_time_model(
        model,
        X_train,
        y_train,
        X_test,
        y_test,
        x_prep=x_prep,
        epochs=epochs,
        lr=lr,
        seed=seed,
        device=device,
        dtype=dtype,
        verbose=verbose,
        print_every=print_every,
    )
    result["n_pmm"] = int(n_pmm)
    result["eval_batch_size"] = None if eval_batch_size is None else int(eval_batch_size)
    result["model_type"] = "PMM observable"
    result["learned_observable"] = True
    result["model_scope_note"] = (
        "Observable PMM learns both a Hamiltonian and a symmetric observable matrix."
    )
    return result


def train_pmm_fixed_observable_model(
    X_train,
    y_train,
    X_test,
    y_test,
    O_fixed,
    x_prep=0.0,
    epochs=4000,
    lr=1e-2,
    init_scale=1e-2,
    eval_batch_size=DEFAULT_PMM_EVAL_BATCH_SIZE,
    seed=GLOBAL_SEED,
    device=DEVICE,
    dtype=TORCH_DTYPE,
    verbose=True,
    print_every=500,
):
    """Train a fixed observable PMM from flat arrays and return a result dict.
    """
    model = PMMFixedObservableTimeEvolution(
        O_fixed,
        init_scale=init_scale,
        dtype=dtype,
        eval_batch_size=eval_batch_size,
    )
    result = _train_pmm_time_model(
        model,
        X_train,
        y_train,
        X_test,
        y_test,
        x_prep=x_prep,
        epochs=epochs,
        lr=lr,
        seed=seed,
        device=device,
        dtype=dtype,
        verbose=verbose,
        print_every=print_every,
    )
    result["n_pmm"] = int(model.n)
    result["eval_batch_size"] = None if eval_batch_size is None else int(eval_batch_size)
    result["model_type"] = "PMM fixed compressed observable"
    result["learned_observable"] = False
    result["fixed_observable_source"] = "exact compressed observable"
    result["dimension_matched_to_compressed_exact"] = True
    result["basis_matched_to_compressed_exact"] = False
    result["model_scope_note"] = (
        "Fixed-observable PMM learns a Hamiltonian while using the matched exact "
        "compressed observable matrix as a fixed operator in the PMM space."
    )
    return result


def compact_model_result(result: dict):
    """Remove torch modules from a result dict while keeping standardized prediction arrays.

    Codex and ChatGPT helped standardize this saved result format across PMM
    and GRU time evolution experiments.
    """
    keep = {
        key: value
        for key, value in result.items()
        if key not in {
            "model",
            "Y_train_pred",
            "y_train_pred_flat",
            "Y_train_pred_seq",
        }
    }

    if "y_test_pred_flat" in result:
        keep["y_test_pred_flat"] = np.asarray(result["y_test_pred_flat"])

    if "Y_test_pred_seq" in result:
        keep["Y_test_pred_seq"] = np.asarray(result["Y_test_pred_seq"])

    return keep


def comparison_row(label, family, result, n_pmm=None):
    """Convert a learned model result dict into one summary table row.

    This table row format keeps PMM and GRU diagnostics comparable in the
    result notebook and plotting notebook, partially implemented by Codex.
    """
    stats = result["test_stats"]
    return {
        "model": label,
        "model_family": family,
        "n_pmm": np.nan if n_pmm is None else int(n_pmm),
        "rank": np.nan,
        "effective_dimension": np.nan if n_pmm is None else int(n_pmm),
        "mean_abs_test_error": float(stats["mean_abs_error"]),
        "max_abs_test_error": float(stats["max_abs_error"]),
        "rms_test_error": float(stats["rms_error"]),
        "test_mse": float(stats["mse"]),
        "parameter_count": int(result["parameter_count"]),
        "train_time_s": float(result["train_time_s"]),
        "best_epoch": int(result["best_epoch"]),
        "best_train_mse": float(result["best_train_mse"]),
        "psi0_projected_norm": np.nan,
        "psi0_projected_weight": np.nan,
    }


def compressed_exact_comparison_row(label, result, rank):
    """Convert a compressed exact result dict into one summary table row.

    This row keeps compression diagnostics separate from learned model
    diagnostics in the time evolution tables, the logic was suggested by Codex.
    """
    stats = result["test_stats"]
    rank = int(rank)
    return {
        "model": label,
        "model_family": "compressed_exact",
        "n_pmm": np.nan,
        "rank": rank,
        "effective_dimension": rank,
        "mean_abs_test_error": float(stats["mean_abs_error"]),
        "max_abs_test_error": float(stats["max_abs_error"]),
        "rms_test_error": float(stats["rms_error"]),
        "test_mse": float(stats["mse"]),
        "parameter_count": np.nan,
        "train_time_s": 0.0,
        "best_epoch": np.nan,
        "best_train_mse": np.nan,
        "psi0_projected_norm": float(result.get("psi0_projected_norm", np.nan)),
        "psi0_projected_weight": float(result.get("psi0_projected_norm", np.nan)) ** 2,
    }


def matched_pmm_compressed_error_rows(pmm_results_by_n, compressed_exact_by_rank, model_family):
    """Compare matched PMM and compressed exact predictions by dimension and return table rows."""
    rows = []
    common_dims = sorted(set(map(int, pmm_results_by_n.keys())) & set(map(int, compressed_exact_by_rank.keys())))
    for dim in common_dims:
        pmm_result = pmm_results_by_n[dim]
        compressed_result = compressed_exact_by_rank[dim]
        stats = compute_error_stats_with_mse(compressed_result["Y_test_pred"], pmm_result["Y_test_pred"])
        rows.append(
            {
                "dimension": int(dim),
                "model_family": model_family,
                "mean_abs_error_vs_compressed_exact": float(stats["mean_abs_error"]),
                "max_abs_error_vs_compressed_exact": float(stats["max_abs_error"]),
                "rms_error_vs_compressed_exact": float(stats["rms_error"]),
                "mse_vs_compressed_exact": float(stats["mse"]),
                "compressed_mean_abs_error_vs_full": float(compressed_result["test_stats"]["mean_abs_error"]),
                "pmm_mean_abs_error_vs_full": float(pmm_result["test_stats"]["mean_abs_error"]),
                "psi0_projected_norm": float(compressed_result.get("psi0_projected_norm", np.nan)),
                "psi0_projected_weight": float(compressed_result.get("psi0_projected_norm", np.nan)) ** 2,
            }
        )
    return rows
